language: python
python:
  - "3.8"

before_install:
  - pip install pycodestyle
  - pip install codecov

# install dependencies
install:
  - pip install -r requirements.txt

script:
  - coverage erase
  - coverage run --source="src/" -m unittest discover -v && coverage html
  - coverage report
# check style
  - pycodestyle src/ --ignore=E722,E501,E402

after_success:
  - codecov

