language: python
python:
  - "3.8"

before_install:
  - pip install pycodestyle

install:
  - pip install -r requirements.txt

script:
  - pytest "tests/"
  - coverage report
  - pycodestyle src/ --ignore=E722,E501,E402
