language: python
python:
  - "3.7"

before_install:
  - pip install pycodestyle

install:
  - pip install -r requirements.txt

script:
  - pytest -m pytest tests/
  - coverage run --source="src/" -m pytest
  - pycodestyle src/ --ignore=E722,E501,E402
